import { initializeApp,getApps } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js';
import { getAuth,onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js';
import { getFirestore,doc,getDoc,collection,addDoc,updateDoc,serverTimestamp,arrayUnion } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js';
import { firebaseConfig,QUOTES_COLLECTION } from './firebase-config.js';
const app=getApps().length?getApps()[0]:initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);
const params=new URLSearchParams(location.search),quoteId=params.get('quoteId'),devisId=params.get('devisId');let quote=null,devis=null,company={companyName:'MOVENTRA TRANSPORT ET DÉMÉNAGEMENT',legalName:'9565-1147 Québec inc.',neq:'1182032350',tps:'772945770RT0001',tvq:'1233721499TQ0001',phone:'438-229-9722',email:'info@moventratransport.ca',address:'',conditions:'',thanks:'Merci de votre confiance.',signatureData:''};
const val=(o,...ks)=>{for(const k of ks){const v=o?.[k];if(v!==undefined&&v!==null&&String(v).trim()!=='')return String(v).trim()}return''};const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));const money=n=>new Intl.NumberFormat('fr-CA',{style:'currency',currency:'CAD'}).format(Number(n)||0);const dateInput=d=>{const x=d?new Date(d):new Date();return isNaN(x)?'':x.toISOString().slice(0,10)};const fmtDate=s=>s?new Intl.DateTimeFormat('fr-CA',{dateStyle:'long'}).format(new Date(s+'T12:00:00')):'—';
onAuthStateChanged(auth,u=>u?init():location.replace('login.html?required=1'));
async function init(){try{const s=await getDoc(doc(db,'parametres','entreprise'));if(s.exists())company={...company,...s.data()}}catch(e){console.warn(e)}if(quoteId){const s=await getDoc(doc(db,QUOTES_COLLECTION,quoteId));if(s.exists())quote={id:s.id,...s.data()}}if(devisId){const s=await getDoc(doc(db,'devis',devisId));if(s.exists())devis={id:s.id,...s.data()}}fill();if(params.get('action')==='print')setTimeout(downloadPdf,900);if(params.get('action')==='share')setTimeout(sharePdf,900)}
function fill(){const source=devis||{};$('clientName').value=source.clientName||val(quote,'name','nom');$('clientPhone').value=source.clientPhone||val(quote,'phone','telephone');$('clientEmail').value=source.clientEmail||val(quote,'email','courriel');$('serviceDate').value=source.serviceDate||val(quote,'date','dateSouhaitee','desiredDate');$('depart').value=source.depart||val(quote,'address','depart');$('destination').value=source.destination||val(quote,'destination','adresseArrivee','arrivalAddress');$('propertyType').value=source.propertyType||val(quote,'propertyType','typeLogement');$('validUntil').value=source.validUntil||dateInput(Date.now()+14*86400000);$('tpsRate').value=source.tpsRate??5;$('tvqRate').value=source.tvqRate??9.975;$('conditions').value=source.conditions||company.conditions||$('conditions').value;$('clientNote').value=source.clientNote||val(quote,'message','details');$('linesBody').innerHTML='';const lines=source.lines?.length?source.lines:[{description:val(quote,'service')||'Service de déménagement',qty:1,unitPrice:Number(val(quote,'montantAdmin','estimation'))||0}];lines.forEach(addLine);setStatus(source.status||'brouillon');$('quoteNumberLabel').textContent=source.number||'Nouveau devis';$('previewNumber').textContent=source.number||'DEVIS EN PRÉPARATION';bindInputs();render()}
function addLine(line={description:'',qty:1,unitPrice:0}){const tr=document.createElement('tr');tr.innerHTML=`<td><input class="desc" value="${esc(line.description)}" placeholder="Service"></td><td><input class="qty" type="number" min="0" step="1" value="${Number(line.qty)||1}"></td><td><input class="price" type="number" min="0" step="0.01" value="${Number(line.unitPrice)||0}"></td><td class="lineTotal">${money((Number(line.qty)||0)*(Number(line.unitPrice)||0))}</td><td><button type="button" class="removeLine">×</button></td>`;tr.querySelector('.removeLine').onclick=()=>{tr.remove();render()};tr.querySelectorAll('input').forEach(i=>i.addEventListener('input',render));$('linesBody').appendChild(tr)}
function lines(){return [...$('linesBody').querySelectorAll('tr')].map(tr=>({description:tr.querySelector('.desc').value.trim(),qty:Number(tr.querySelector('.qty').value)||0,unitPrice:Number(tr.querySelector('.price').value)||0})).filter(x=>x.description||x.qty||x.unitPrice)}
function totals(){const subtotal=lines().reduce((s,x)=>s+x.qty*x.unitPrice,0),tps=subtotal*(Number($('tpsRate').value)||0)/100,tvq=subtotal*(Number($('tvqRate').value)||0)/100;return{subtotal,tps,tvq,total:subtotal+tps+tvq}}
function bindInputs(){document.querySelectorAll('input,textarea').forEach(i=>{if(!i.closest('#linesBody'))i.addEventListener('input',render)})}
function render(){const t=totals();$('subtotalLabel').textContent=$('pSubtotal').textContent=money(t.subtotal);$('tpsLabel').textContent=$('pTps').textContent=money(t.tps);$('tvqLabel').textContent=$('pTvq').textContent=money(t.tvq);$('totalLabel').textContent=$('pTotal').textContent=money(t.total);[...$('linesBody').querySelectorAll('tr')].forEach(tr=>tr.querySelector('.lineTotal').textContent=money((Number(tr.querySelector('.qty').value)||0)*(Number(tr.querySelector('.price').value)||0)));$('previewDates').textContent=`Créé le ${fmtDate(dateInput(new Date()))} · Valide jusqu’au ${fmtDate($('validUntil').value)}`;$('previewCompany').innerHTML=`<b>${esc(company.companyName)}</b><br>${esc(company.legalName)}<br>${company.address?esc(company.address)+'<br>':''}NEQ : ${esc(company.neq)}<br>TPS : ${esc(company.tps)}<br>TVQ : ${esc(company.tvq)}<br>${esc(company.phone)} · ${esc(company.email)}`;$('previewClient').innerHTML=`<b>${esc($('clientName').value||'—')}</b><br>${esc($('clientPhone').value)}<br>${esc($('clientEmail').value)}<br>${esc($('depart').value)}${$('destination').value?'<br>→ '+esc($('destination').value):''}`;$('previewLines').innerHTML=lines().map(x=>`<tr><td>${esc(x.description)}</td><td>${x.qty}</td><td>${money(x.unitPrice)}</td><td>${money(x.qty*x.unitPrice)}</td></tr>`).join('')||'<tr><td colspan="4">Aucun service</td></tr>';$('previewNotes').innerHTML=`${$('serviceDate').value?`<div class="previewBox"><small>DATE DU SERVICE</small><p>${fmtDate($('serviceDate').value)}${$('propertyType').value?' · '+esc($('propertyType').value):''}</p></div>`:''}${$('clientNote').value?`<div class="previewBox" style="margin-top:10px"><small>NOTE</small><p>${esc($('clientNote').value).replace(/\n/g,'<br>')}</p></div>`:''}<div class="previewBox" style="margin-top:10px"><small>CONDITIONS</small><p>${esc($('conditions').value).replace(/\n/g,'<br>')}</p></div>`;if(company.signatureData){$('signatureWrap').classList.remove('hidden');$('signatureImg').src=company.signatureData;$('signatureName').textContent=company.companyName}}
function payload(status){const t=totals();return{quoteId:quoteId||devis?.quoteId||'',number:devis?.number||'',status,clientName:$('clientName').value.trim(),clientPhone:$('clientPhone').value.trim(),clientEmail:$('clientEmail').value.trim(),serviceDate:$('serviceDate').value,depart:$('depart').value.trim(),destination:$('destination').value.trim(),propertyType:$('propertyType').value.trim(),validUntil:$('validUntil').value,tpsRate:Number($('tpsRate').value)||0,tvqRate:Number($('tvqRate').value)||0,conditions:$('conditions').value.trim(),clientNote:$('clientNote').value.trim(),lines:lines(),...t,updatedAt:serverTimestamp()}}
async function save(status='brouillon'){const btn=$('saveDraftBtn');btn.disabled=true;try{let data=payload(status);if(!devis){data.number=`DEV-${new Date().getFullYear()}-${String(Date.now()).slice(-6)}`;data.createdAt=serverTimestamp();const ref=await addDoc(collection(db,'devis'),data);devis={id:ref.id,...data};history.replaceState(null,'',`devis.html?devisId=${ref.id}${quoteId?`&quoteId=${quoteId}`:''}`)}else{await updateDoc(doc(db,'devis',devis.id),data);devis={...devis,...data}}if(quoteId){const label=status==='envoye'?'Devis envoyé':status==='accepte'?'Devis accepté':'Devis enregistré';await updateDoc(doc(db,QUOTES_COLLECTION,quoteId),{devisId:devis.id,devisNumber:devis.number,devisStatus:status,status:status==='envoye'?'devis_envoye':status==='accepte'?'acceptee':quote?.status||'nouvelle',updatedAt:serverTimestamp(),timeline:arrayUnion({label,at:new Date().toISOString()})})}$('quoteNumberLabel').textContent=devis.number;$('previewNumber').textContent=devis.number;$('saveInfo').textContent='Enregistré';setStatus(status);return devis}catch(e){console.error(e);alert('Erreur lors de l’enregistrement : '+(e.message||e.code));throw e}finally{btn.disabled=false}}
function setStatus(s){const labels={brouillon:'Brouillon',envoye:'Devis envoyé',accepte:'Accepté',refuse:'Refusé'};$('statusPill').className=`statusPill status-${s}`;$('statusPill').textContent=labels[s]||s}
async function makePdfBlob(){render();const el=$('quotePreview'),opt={margin:[7,7,7,7],filename:`${devis?.number||'devis-moventra'}.pdf`,image:{type:'jpeg',quality:.97},html2canvas:{scale:2,useCORS:true,backgroundColor:'#ffffff'},jsPDF:{unit:'mm',format:'a4',orientation:'portrait'},pagebreak:{mode:['avoid-all','css','legacy']}};return html2pdf().set(opt).from(el).outputPdf('blob')}
async function downloadPdf(){if(!devis)await save('brouillon');const blob=await makePdfBlob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${devis.number}.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000)}
function emailText(){return `Bonjour ${$('clientName').value.trim()},\n\nVeuillez trouver ci-joint votre devis Moventra pour le service demandé.\n\nNuméro du devis : ${devis?.number||''}\nMontant total : ${money(totals().total)}\nValide jusqu’au : ${fmtDate($('validUntil').value)}\n\nPour accepter le devis, veuillez répondre à ce courriel ou communiquer avec nous au 438-229-9722.\n\nMerci,\nMoventra Transport et Déménagement`}
async function sharePdf(){if(!devis)await save('envoye');else await save('envoye');const blob=await makePdfBlob(),file=new File([blob],`${devis.number}.pdf`,{type:'application/pdf'}),subject=`Votre devis Moventra ${devis.number}`;if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:subject,text:emailText()});return}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);location.href=`https://mail.google.com/mail/?view=cm&fs=1&to=${encodeURIComponent($('clientEmail').value)}&su=${encodeURIComponent(subject)}&body=${encodeURIComponent(emailText())}`}
$('addLineBtn').onclick=()=>addLine();$('saveDraftBtn').onclick=()=>save('brouillon');$('markSentBtn').onclick=()=>save('envoye');$('downloadBtn').onclick=downloadPdf;$('shareBtn').onclick=sharePdf;$('markAcceptedBtn').onclick=async()=>{if(confirm('Confirmer que le client a accepté ce devis ?')){await save('accepte');alert('Devis marqué comme accepté. La soumission est maintenant acceptée.')}};
